vim.opt.cursorline = true
vim.opt.complete = { ".^5", "o^5" }
vim.opt.completeopt = { "fuzzy", "menuone", "noselect", "popup" }
vim.opt.autocomplete = true
vim.opt.pumborder = 'rounded'
vim.opt.pumheight = 7
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.termguicolors = true
vim.o.laststatus = 3
-- vim.o.cmdheight = 0
